//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectionSQL_webAPI_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginDetail
    {
        public int UserLoginDetailsId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> LoginAttemp { get; set; }
        public Nullable<decimal> SysGeneratedEmailCode { get; set; }
        public Nullable<decimal> SysGeneratedMobileCode { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public Nullable<bool> IsPhoneNumberVerified { get; set; }
        public Nullable<bool> IsForgotPassword { get; set; }
        public Nullable<System.DateTime> LastPasswordResetDate { get; set; }
        public string LoginMachineIp { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<bool> IsActiveUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual User User { get; set; }
    }
}
