//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectionSQL_webAPI_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSecAnsDetail
    {
        public int UserSecAnsDetailsId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> SecurityQuestionId { get; set; }
        public Nullable<int> AnswerId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual SecurityQuestion SecurityQuestion { get; set; }
        public virtual User User { get; set; }
    }
}
